version: '3.8'
services:
  java:
    image: openjdk:11-jdk-oracle
    container_name: WirtschaftstagWS
    command: java -jar /app.jar
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - ./target/app-1.0.jar:/app.jar
  mysql:
    image: mysql
    container_name: WirtschaftstagDB
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: usr
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/mockdata.sql:/docker-entrypoint-initdb.d/2.sql
