/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class custom_NativeTableModel */

#ifndef _Included_custom_NativeTableModel
#define _Included_custom_NativeTableModel
#ifdef __cplusplus
extern "C" {
#endif
#undef custom_NativeTableModel_serialVersionUID
#define custom_NativeTableModel_serialVersionUID 1LL
/*
 * Class:     custom_NativeTableModel
 * Method:    getRowCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_custom_NativeTableModel_getRowCount
  (JNIEnv *, jobject);

/*
 * Class:     custom_NativeTableModel
 * Method:    getColumnCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_custom_NativeTableModel_getColumnCount
  (JNIEnv *, jobject);

/*
 * Class:     custom_NativeTableModel
 * Method:    getColumnName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_custom_NativeTableModel_getColumnName
  (JNIEnv *, jobject, jint);

/*
 * Class:     custom_NativeTableModel
 * Method:    getColumnClass
 * Signature: (I)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_custom_NativeTableModel_getColumnClass
  (JNIEnv *, jobject, jint);

/*
 * Class:     custom_NativeTableModel
 * Method:    isCellEditable
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_custom_NativeTableModel_isCellEditable
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     custom_NativeTableModel
 * Method:    getValueAt
 * Signature: (II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_custom_NativeTableModel_getValueAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     custom_NativeTableModel
 * Method:    setValueAt
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_custom_NativeTableModel_setValueAt
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     custom_NativeTableModel
 * Method:    addItem
 * Signature: (Lmodels/Bottle;)V
 */
JNIEXPORT void JNICALL Java_custom_NativeTableModel_addItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     custom_NativeTableModel
 * Method:    removeRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_custom_NativeTableModel_removeRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     custom_NativeTableModel
 * Method:    loadFromFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_custom_NativeTableModel_loadFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     custom_NativeTableModel
 * Method:    saveToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_custom_NativeTableModel_saveToFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
