version: '3.8'
services:
  tomcat:
    image: tomcat
    container_name: ProductsWS
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./target:/usr/local/tomcat/webapps/
  mysqlDB:
    image: mysql
    container_name: ProductsDB
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: usr
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./scripts/creates.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/inserts.sql:/docker-entrypoint-initdb.d/2.sql
